/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tls_message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tls_message.pb-c.h"
void   tls_message__init
                     (TlsMessage         *message)
{
  static TlsMessage init_value = TLS_MESSAGE__INIT;
  *message = init_value;
}
size_t tls_message__get_packed_size
                     (const TlsMessage *message)
{
  assert(message->base.descriptor == &tls_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tls_message__pack
                     (const TlsMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tls_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tls_message__pack_to_buffer
                     (const TlsMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tls_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TlsMessage *
       tls_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TlsMessage *)
     protobuf_c_message_unpack (&tls_message__descriptor,
                                allocator, len, data);
}
void   tls_message__free_unpacked
                     (TlsMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tls_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_remote_req__init
                     (RsaRemoteReq         *message)
{
  static RsaRemoteReq init_value = RSA_REMOTE_REQ__INIT;
  *message = init_value;
}
size_t rsa_remote_req__get_packed_size
                     (const RsaRemoteReq *message)
{
  assert(message->base.descriptor == &rsa_remote_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_remote_req__pack
                     (const RsaRemoteReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_remote_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_remote_req__pack_to_buffer
                     (const RsaRemoteReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_remote_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaRemoteReq *
       rsa_remote_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaRemoteReq *)
     protobuf_c_message_unpack (&rsa_remote_req__descriptor,
                                allocator, len, data);
}
void   rsa_remote_req__free_unpacked
                     (RsaRemoteReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rsa_remote_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsa_remote_rsp__init
                     (RsaRemoteRsp         *message)
{
  static RsaRemoteRsp init_value = RSA_REMOTE_RSP__INIT;
  *message = init_value;
}
size_t rsa_remote_rsp__get_packed_size
                     (const RsaRemoteRsp *message)
{
  assert(message->base.descriptor == &rsa_remote_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsa_remote_rsp__pack
                     (const RsaRemoteRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsa_remote_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsa_remote_rsp__pack_to_buffer
                     (const RsaRemoteRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsa_remote_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RsaRemoteRsp *
       rsa_remote_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RsaRemoteRsp *)
     protobuf_c_message_unpack (&rsa_remote_rsp__descriptor,
                                allocator, len, data);
}
void   rsa_remote_rsp__free_unpacked
                     (RsaRemoteRsp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rsa_remote_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tls_message__field_descriptors[4] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(TlsMessage, has_version),
    offsetof(TlsMessage, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(TlsMessage, has_id),
    offsetof(TlsMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TlsMessage, private_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encryt_txt",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TlsMessage, encryt_txt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tls_message__field_indices_by_name[] = {
  3,   /* field[3] = encryt_txt */
  1,   /* field[1] = id */
  2,   /* field[2] = private_key */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange tls_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tls_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tls_message",
  "TlsMessage",
  "TlsMessage",
  "",
  sizeof(TlsMessage),
  4,
  tls_message__field_descriptors,
  tls_message__field_indices_by_name,
  1,  tls_message__number_ranges,
  (ProtobufCMessageInit) tls_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_remote_req__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteReq, has_id),
    offsetof(RsaRemoteReq, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteReq, has_version),
    offsetof(RsaRemoteReq, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteReq, has_type),
    offsetof(RsaRemoteReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "from_len",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteReq, has_from_len),
    offsetof(RsaRemoteReq, from_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "padding",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteReq, has_padding),
    offsetof(RsaRemoteReq, padding),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RsaRemoteReq, has_public_key),
    offsetof(RsaRemoteReq, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RsaRemoteReq, has_private_key),
    offsetof(RsaRemoteReq, private_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RsaRemoteReq, has_msg),
    offsetof(RsaRemoteReq, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key_len",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteReq, has_private_key_len),
    offsetof(RsaRemoteReq, private_key_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_remote_req__field_indices_by_name[] = {
  3,   /* field[3] = from_len */
  0,   /* field[0] = id */
  7,   /* field[7] = msg */
  4,   /* field[4] = padding */
  6,   /* field[6] = private_key */
  8,   /* field[8] = private_key_len */
  5,   /* field[5] = public_key */
  2,   /* field[2] = type */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange rsa_remote_req__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 7, 4 },
  { 10, 5 },
  { 15, 8 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor rsa_remote_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rsa_remote_req",
  "RsaRemoteReq",
  "RsaRemoteReq",
  "",
  sizeof(RsaRemoteReq),
  9,
  rsa_remote_req__field_descriptors,
  rsa_remote_req__field_indices_by_name,
  5,  rsa_remote_req__number_ranges,
  (ProtobufCMessageInit) rsa_remote_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsa_remote_rsp__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteRsp, has_id),
    offsetof(RsaRemoteRsp, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteRsp, has_version),
    offsetof(RsaRemoteRsp, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteRsp, has_type),
    offsetof(RsaRemoteRsp, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "padding",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RsaRemoteRsp, has_padding),
    offsetof(RsaRemoteRsp, padding),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RsaRemoteRsp, has_msg),
    offsetof(RsaRemoteRsp, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsa_remote_rsp__field_indices_by_name[] = {
  0,   /* field[0] = id */
  4,   /* field[4] = msg */
  3,   /* field[3] = padding */
  2,   /* field[2] = type */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange rsa_remote_rsp__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 7, 3 },
  { 12, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rsa_remote_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rsa_remote_rsp",
  "RsaRemoteRsp",
  "RsaRemoteRsp",
  "",
  sizeof(RsaRemoteRsp),
  5,
  rsa_remote_rsp__field_descriptors,
  rsa_remote_rsp__field_indices_by_name,
  3,  rsa_remote_rsp__number_ranges,
  (ProtobufCMessageInit) rsa_remote_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
